"""modify_booking_table_add_pdf_table

Revision ID: 18686cbbbadf
Revises: 42bbd0ff114f
Create Date: 2022-07-26 11:57:57.465780

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '18686cbbbadf'
down_revision = '42bbd0ff114f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdf_prints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('data', sa.LargeBinary(length=500000.0), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('pdf_type', sa.String(), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pdf_prints_id'), 'pdf_prints', ['id'], unique=False)
    op.add_column('booking', sa.Column('records_approved', sa.Boolean(), nullable=True))
    op.add_column('booking', sa.Column('approver_name', sa.String(), nullable=True))
    op.add_column('booking', sa.Column('interpreter_signed', sa.Boolean(), nullable=True))
    op.add_column('booking', sa.Column('interpreter_signdate', sa.String(), nullable=True))
    op.add_column('booking', sa.Column('qr_signed', sa.Boolean(), nullable=True))
    op.add_column('booking', sa.Column('qr_signdate', sa.String(), nullable=True))
    op.add_column('booking', sa.Column('fees_gst', sa.Float(), nullable=True))
    op.add_column('booking', sa.Column('fees_total', sa.Float(), nullable=True))
    op.add_column('booking', sa.Column('expense_gst', sa.Float(), nullable=True))
    op.add_column('booking', sa.Column('expense_total', sa.Float(), nullable=True))
    op.add_column('booking', sa.Column('invoice_total', sa.Float(), nullable=True))
    op.add_column('booking', sa.Column('invoice_date', sa.String(), nullable=True))
    op.add_column('booking', sa.Column('invoice_number', sa.String(), nullable=True))
    op.add_column('booking', sa.Column('adm_detail', sa.String(), nullable=True))
    op.add_column('booking', sa.Column('adm_updated_by', sa.String(), nullable=True))
    op.add_column('booking', sa.Column('form_sender', sa.String(), nullable=True))
    op.add_column('booking', sa.Column('form_sender_email', sa.String(), nullable=True))
    op.add_column('booking', sa.Column('form_recipient_email', sa.String(), nullable=True))
    op.add_column('booking', sa.Column('form_sent_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('booking', sa.Column('invoice_sender', sa.String(), nullable=True))
    op.add_column('booking', sa.Column('invoice_sender_email', sa.String(), nullable=True))
    op.add_column('booking', sa.Column('invoice_recipient_email', sa.String(), nullable=True))
    op.add_column('booking', sa.Column('invoice_sent_date', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('booking', 'spkl3_rate')
    op.drop_column('booking', 'spkl2_rate')
    op.drop_column('booking', 'spkl4_rate')
    op.drop_column('booking', 'cart_rate')
    op.drop_column('booking', 'asl1_rate')
    op.drop_column('booking', 'asl2_rate')
    op.drop_column('booking', 'spkl1_rate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('spkl1_rate', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('booking', sa.Column('asl2_rate', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('booking', sa.Column('asl1_rate', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('booking', sa.Column('cart_rate', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('booking', sa.Column('spkl4_rate', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('booking', sa.Column('spkl2_rate', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('booking', sa.Column('spkl3_rate', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('booking', 'invoice_sent_date')
    op.drop_column('booking', 'invoice_recipient_email')
    op.drop_column('booking', 'invoice_sender_email')
    op.drop_column('booking', 'invoice_sender')
    op.drop_column('booking', 'form_sent_date')
    op.drop_column('booking', 'form_recipient_email')
    op.drop_column('booking', 'form_sender_email')
    op.drop_column('booking', 'form_sender')
    op.drop_column('booking', 'adm_updated_by')
    op.drop_column('booking', 'adm_detail')
    op.drop_column('booking', 'invoice_number')
    op.drop_column('booking', 'invoice_date')
    op.drop_column('booking', 'invoice_total')
    op.drop_column('booking', 'expense_total')
    op.drop_column('booking', 'expense_gst')
    op.drop_column('booking', 'fees_total')
    op.drop_column('booking', 'fees_gst')
    op.drop_column('booking', 'qr_signdate')
    op.drop_column('booking', 'qr_signed')
    op.drop_column('booking', 'interpreter_signdate')
    op.drop_column('booking', 'interpreter_signed')
    op.drop_column('booking', 'approver_name')
    op.drop_column('booking', 'records_approved')
    op.drop_index(op.f('ix_pdf_prints_id'), table_name='pdf_prints')
    op.drop_table('pdf_prints')
    # ### end Alembic commands ###
