"""add_qr_signed_note_to_booking_table

Revision ID: 3050d774eb6e
Revises: 656b7778ac27
Create Date: 2025-10-29 05:09:54.633783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3050d774eb6e'
down_revision = '656b7778ac27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('qr_signed_note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'qr_signed_note')
    # ### end Alembic commands ###
