"""change_booking_table_adm_audit

Revision ID: 37ae0065c512
Revises: d47d3d1c1b6e
Create Date: 2024-03-10 20:16:27.791463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37ae0065c512'
down_revision = 'd47d3d1c1b6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('adm_audit_flag', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'adm_audit_flag')
    # ### end Alembic commands ###
