"""add_ceis_justin_fields_to_booking_cases

Revision ID: 4b7c8d9e0a1f
Revises: 3050d774eb6e
Create Date: 2025-12-16 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b7c8d9e0a1f'
down_revision = '3050d774eb6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add CEIS/JUSTIN tracking fields
    op.add_column('booking_cases', sa.Column('justin_no', sa.String(), nullable=True))
    op.add_column('booking_cases', sa.Column('physical_file_id', sa.String(), nullable=True))
    op.add_column('booking_cases', sa.Column('appearance_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking_cases', 'appearance_id')
    op.drop_column('booking_cases', 'physical_file_id')
    op.drop_column('booking_cases', 'justin_no')
    # ### end Alembic commands ###
