"""add_booking_cases_table

Revision ID: 4e967094c2c5
Revises: a854770251bb
Create Date: 2023-02-10 15:30:10.371483

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4e967094c2c5'
down_revision = 'a854770251bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(), nullable=True),
    sa.Column('case_name', sa.String(), nullable=True),
    sa.Column('room', sa.String(), nullable=True),
    sa.Column('case_type', sa.String(), nullable=True),
    sa.Column('court_level', sa.String(), nullable=True),
    sa.Column('court_class', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('interpret_for', sa.String(), nullable=True),
    sa.Column('remote_registry', sa.String(), nullable=True),
    sa.Column('remote_location_id', sa.Integer(), nullable=True),
    sa.Column('van_registry', sa.String(), nullable=True),
    sa.Column('van_location_id', sa.Integer(), nullable=True),
    sa.Column('federal', sa.Boolean(), nullable=False),
    sa.Column('prosecutor', sa.String(), nullable=True),
    sa.Column('bilingual', sa.Boolean(), nullable=True),
    sa.Column('interpretation_mode', sa.String(), nullable=True),
    sa.Column('method_of_appearance', postgresql.ENUM('In-Person', 'MS Teams', 'Via Teleconference', 'RIS', name='booking_method_of_appearance', create_type=False), server_default='In-Person', nullable=False),
    sa.Column('requested_by', postgresql.ENUM('Court', 'Crown', 'Applicant', 'Defence', 'Respondent', name='booking_requested_by', create_type=False), server_default='Court', nullable=False),
    sa.Column('interpreter_language_id', sa.Integer(), nullable=True),
    sa.Column('booking_date_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['booking_date_id'], ['booking_dates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interpreter_language_id'], ['interpreter_language.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_cases_id'), 'booking_cases', ['id'], unique=False)
    op.drop_column('booking_dates', 'court_class')
    op.drop_column('booking_dates', 'reason')
    op.drop_column('booking_dates', 'prosecutor')
    op.drop_column('booking_dates', 'location_id')
    op.drop_column('booking_dates', 'registry')
    op.drop_column('booking_dates', 'court_level')
    op.drop_column('booking_dates', 'requested_by')
    op.drop_column('booking_dates', 'federal')
    op.drop_column('booking_dates', 'case_type')
    op.drop_column('booking_dates', 'file')
    op.drop_column('booking_dates', 'bilingual')
    op.drop_column('booking_dates', 'languages')
    op.drop_column('booking_dates', 'room')
    op.drop_column('booking_dates', 'case_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_dates', sa.Column('case_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('booking_dates', sa.Column('room', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('booking_dates', sa.Column('languages', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('booking_dates', sa.Column('bilingual', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('booking_dates', sa.Column('file', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('booking_dates', sa.Column('case_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('booking_dates', sa.Column('federal', sa.BOOLEAN(), autoincrement=False, nullable=False, server_default='f'))
    op.add_column('booking_dates', sa.Column('requested_by', postgresql.ENUM('Court', 'Crown', 'Applicant', 'Defence', 'Respondent', name='booking_requested_by'), server_default=sa.text("'Court'::booking_requested_by"), autoincrement=False, nullable=False))
    op.add_column('booking_dates', sa.Column('court_level', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('booking_dates', sa.Column('registry', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('booking_dates', sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('booking_dates', sa.Column('prosecutor', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('booking_dates', sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('booking_dates', sa.Column('court_class', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_booking_cases_id'), table_name='booking_cases')
    op.drop_table('booking_cases')
    # ### end Alembic commands ###
