"""update_interpreter__booking_tables

Revision ID: 5a9c50bbc416
Revises: 9a9558afa1f2
Create Date: 2022-04-26 11:23:15.637739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a9c50bbc416'
down_revision = '9a9558afa1f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('spkl1_rate', sa.Float(), nullable=True))
    op.add_column('booking', sa.Column('spkl2_rate', sa.Float(), nullable=True))
    op.add_column('booking', sa.Column('spkl3_rate', sa.Float(), nullable=True))
    op.add_column('booking', sa.Column('spkl4_rate', sa.Float(), nullable=True))
    op.add_column('booking', sa.Column('asl1_rate', sa.Float(), nullable=True))
    op.add_column('booking', sa.Column('asl2_rate', sa.Float(), nullable=True))
    op.add_column('booking', sa.Column('cart_rate', sa.Float(), nullable=True))
    op.add_column('interpreter', sa.Column('language_history', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interpreter', 'language_history')
    op.drop_column('booking', 'cart_rate')
    op.drop_column('booking', 'asl2_rate')
    op.drop_column('booking', 'asl1_rate')
    op.drop_column('booking', 'spkl4_rate')
    op.drop_column('booking', 'spkl3_rate')
    op.drop_column('booking', 'spkl2_rate')
    op.drop_column('booking', 'spkl1_rate')
    # ### end Alembic commands ###
