"""Add indexes on interpreter_language table for language_id,interpreter_id,level fields

Revision ID: 656b7778ac27
Revises: 808308463b67
Create Date: 2024-09-13 20:26:54.820432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '656b7778ac27'
down_revision = '808308463b67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_interpreter_language_interpreter_id'), 'interpreter_language', ['interpreter_id'], unique=False)
    op.create_index(op.f('ix_interpreter_language_language_id'), 'interpreter_language', ['language_id'], unique=False)
    op.create_index(op.f('ix_interpreter_language_level'), 'interpreter_language', ['level'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interpreter_language_level'), table_name='interpreter_language')
    op.drop_index(op.f('ix_interpreter_language_language_id'), table_name='interpreter_language')
    op.drop_index(op.f('ix_interpreter_language_interpreter_id'), table_name='interpreter_language')
    # ### end Alembic commands ###
