"""modified_user_table

Revision ID: 8788b5f3f2db
Revises: 73e5872168e0
Create Date: 2021-12-10 11:30:05.487327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8788b5f3f2db'
down_revision = '73e5872168e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'universal_id')
    op.drop_column('user', 'idir_userid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('idir_userid', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('universal_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
