"""add_court_distance_table

Revision ID: 8bc4f7b9396c
Revises: c3d9430b842c
Create Date: 2022-12-10 19:01:23.702482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bc4f7b9396c'
down_revision = 'c3d9430b842c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('court_distance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('court_id', sa.Integer(), nullable=True),
    sa.Column('interpreter_id', sa.Integer(), nullable=True),
    sa.Column('court_code', sa.String(), nullable=True),
    sa.Column('court_address', sa.String(), nullable=True),
    sa.Column('interpreter_address', sa.String(), nullable=True),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('court_latitude', sa.Float(), nullable=True),
    sa.Column('court_longitude', sa.Float(), nullable=True),
    sa.Column('interpreter_latitude', sa.Float(), nullable=True),
    sa.Column('interpreter_longitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['court_id'], ['court_location.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interpreter_id'], ['interpreter.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_court_distance_id'), 'court_distance', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_court_distance_id'), table_name='court_distance')
    op.drop_table('court_distance')
    # ### end Alembic commands ###
