"""added_booking_and_booking_dates_table

Revision ID: 9e3c434cbfaf
Revises: d47be13b8184
Create Date: 2022-01-14 10:31:21.737490

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9e3c434cbfaf'
down_revision = 'd47be13b8184'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('case_name', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('prosecutor', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('registry', sa.String(), nullable=True),
    sa.Column('room', sa.String(), nullable=True),
    sa.Column('file', sa.String(), nullable=True),
    sa.Column('federal', sa.Boolean(), nullable=False),
    sa.Column('language_name', sa.String(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('interpret_for', postgresql.ENUM('Witness', 'Party', 'Accused', name='booking_interpret_for'), server_default='Witness', nullable=False),
    sa.Column('method_of_appearance', postgresql.ENUM('In-Person', 'MS Teams', 'Via Teleconference', 'RIS', name='booking_method_of_appearance'), server_default='In-Person', nullable=False),
    sa.Column('requested_by', postgresql.ENUM('Court', 'Crown', 'Applicant', 'Defence', 'Respondent', name='booking_requested_by'), server_default='Court', nullable=False),
    sa.Column('status', postgresql.ENUM('Pending', 'Booked', 'Cancelled', name='booking_status'), server_default='Pending', nullable=False),
    sa.Column('interpreter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['interpreter_id'], ['interpreter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_id'), 'booking', ['id'], unique=False)
    op.create_index(op.f('ix_booking_name'), 'booking', ['name'], unique=True)
    op.create_table('booking_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arrivalTime', sa.String(), nullable=True),
    sa.Column('period', postgresql.ENUM('MORNING', 'AFTERNOON', 'WHOLE_DAY', name='booking_period'), server_default='WHOLE_DAY', nullable=False),
    sa.Column('interpreter_id', sa.Integer(), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_dates_id'), 'booking_dates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booking_dates_id'), table_name='booking_dates')
    op.drop_table('booking_dates')
    op.drop_index(op.f('ix_booking_name'), table_name='booking')
    op.drop_index(op.f('ix_booking_id'), table_name='booking')
    op.drop_table('booking')
    op.execute('DROP TYPE booking_period')
    op.execute('DROP TYPE booking_status')
    op.execute('DROP TYPE booking_requested_by')    
    op.execute('DROP TYPE booking_method_of_appearance')
    op.execute('DROP TYPE booking_interpret_for')
    
    # ### end Alembic commands ###
