"""change_booking_date_table

Revision ID: ab3b04d5f223
Revises: f66cba0b8f17
Create Date: 2022-04-18 12:25:56.870144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab3b04d5f223'
down_revision = 'f66cba0b8f17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_dates', sa.Column('court_class', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking_dates', 'court_class')
    # ### end Alembic commands ###
