"""added_geo_status_table

Revision ID: b7ddd26f4423
Revises: 9e3c434cbfaf
Create Date: 2022-02-03 15:19:07.568769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7ddd26f4423'
down_revision = '9e3c434cbfaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    geo_status_table = op.create_table('geo_status',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('next_update_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('update_schedule', sa.String(), nullable=True),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('update_service', sa.String(), nullable=True),
        sa.Column('progress', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geo_status_id'), 'geo_status', ['id'], unique=False)
    op.alter_column('interpreter_language', 'level',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###

    op.bulk_insert(geo_status_table, [
        {'name':'locations',   'description':'All Locations',    'progress':100}, 
        {'name':'interpreters','description':'All Interpreters', 'progress':100}   
    ])



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interpreter_language', 'level',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_geo_status_id'), table_name='geo_status')
    op.drop_table('geo_status')
    # ### end Alembic commands ###
