"""change_booking_case_table_request_by_enums

Revision ID: c12c24a7b8f8
Revises: ca42ee193803
Create Date: 2024-03-16 12:41:17.177391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c12c24a7b8f8'
down_revision = 'ca42ee193803'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE booking_requested_by ADD VALUE IF NOT EXISTS 'Accused'")
    op.execute("ALTER TYPE booking_requested_by ADD VALUE IF NOT EXISTS 'Disputant'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
