"""change_booking_table

Revision ID: c3d9430b842c
Revises: 18686cbbbadf
Create Date: 2022-08-09 14:10:58.802475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3d9430b842c'
down_revision = '18686cbbbadf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('location_id', sa.Integer(), nullable=True))
    op.add_column('booking', sa.Column('location_name', sa.String(), nullable=True))
    op.create_foreign_key('booking_location_id_fkey', 'booking', 'court_location', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('booking_location_id_fkey', 'booking', type_='foreignkey')
    op.drop_column('booking', 'location_name')
    op.drop_column('booking', 'location_id')
    # ### end Alembic commands ###
