"""change_booking_case_table_antcp_start_time

Revision ID: ca42ee193803
Revises: 37ae0065c512
Create Date: 2024-03-16 08:39:53.875399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca42ee193803'
down_revision = '37ae0065c512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_cases', sa.Column('anticipated_start_time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking_cases', 'anticipated_start_time')
    # ### end Alembic commands ###
