"""add_timezone_to_court_location_table

Revision ID: d47d3d1c1b6e
Revises: e4f7c66af479
Create Date: 2023-12-23 15:11:16.766348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd47d3d1c1b6e'
down_revision = 'e4f7c66af479'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('court_location', sa.Column('timezone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('court_location', 'timezone')
    # ### end Alembic commands ###
