---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: court-interpreter-scheduling
    env: dev
    name: web
    role: web
  name: web
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    name: web
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: court-interpreter-scheduling
        env: dev
        name: web
        role: web
      name: web
    spec:
      containers:
        - env:
            - name: PUBLIC_URL
              value: /court-interpreter-scheduling/
            - name: RealIpFrom
              value: 172.51.0.0/16
            - name: AdditionalRealIpFromRules
              value: ''
            - name: WEB_BASE_HREF
              value: /court-interpreter-scheduling/
            - name: IpFilterRules
              value: ''
            - name: API_URL
              value: http://api:8080/api
            - name: API_SERVICE_NAME
              value: api
            - name: API_PATH
              value: /api
          image: web
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /nginx_status
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 60
          name: web
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /nginx_status
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 60
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - web
        from:
          kind: ImageStreamTag
          name: web:dev
          namespace: 1a7b16-tools
      type: ImageChange