FROM node:13.12.0-alpine

WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

COPY package*.json ./
RUN npm install --production
RUN npm install react-scripts@3.4.0 -g

COPY . ./

CMD ["npm", "start", "--BROWSER=none", "CHOKIDAR_USEPOLLING=true"]
