apiVersion: v1
kind: Template
metadata:
  name: ${NAME}
labels:
  project: ${PROJECT}
  service: ${SERVICE_NAME}
objects:
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      name: ${NAME}
    spec:
      replicas: "${{REPLICAS}}"
      revisionHistoryLimit: 10
      selector:
        deploymentconfig: ${NAME}
      strategy:
        type: Rolling
      template:
        metadata:
          labels:
            deploymentconfig: ${NAME}
        spec:
          containers:
            - env:
                - name: JWT_SECRET
                  value: ${JWT_SECRET}
                - name: KEYCLOAK_REALM
                  value: ${KEYCLOAK_REALM}
                - name: KEYCLOAK_CLIENT
                  value: ${KEYCLOAK_CLIENT}
                - name: KEYCLOAK_AUTH_URL
                  value: ${KEYCLOAK_URL}
                - name: KEYCLOAK_SECRET
                  valueFrom:
                    secretKeyRef:
                      key: client-secret
                      name: keycloak-creds
                - name: NODE_ENV
                  value: ${NODE_ENV}
                - name: APPLICATION_PORT
                  value: "${PORT}"
                - name: DB_HOST
                  value: "${DB_SERVICE}"
                - name: POSTGRESQL_USER
                  valueFrom:
                    secretKeyRef:
                      key: ${DB_USERNAME_KEY}
                      name: ${DB_SECRET_NAME}
                - name: POSTGRESQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: ${DB_PASSWORD_KEY}
                      name: ${DB_SECRET_NAME}
                - name: POSTGRESQL_DATABASE
                  value: ${DB_NAME}
                - name: DEPLOYMENT_ENV
                  value: ${DEPLOYMENT_ENV}
                - name: DEPLOYMENT_ENV_HIDDEN_FLAG
                  value: ${DEPLOYMENT_ENV_HIDDEN_FLAG}
              image: ${IMAGE_REGISTRY}/${BUILD_NAMESPACE}/${IMAGE_STREAM_TAG}
              imagePullPolicy: Always
              name: ${NAME}
              ports:
                - containerPort: "${{PORT}}"
              resources:
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
              readinessProbe:
                failureThreshold: 2
                httpGet:
                  path: /api/v1/healthcheck
                  port: "${{PORT}}"
                initialDelaySeconds: 10
                periodSeconds: 30
              livenessProbe:
                failureThreshold: 10
                httpGet:
                  path: /api/v1/healthcheck
                  port: "${{PORT}}"
                  scheme: HTTP
                initialDelaySeconds: 10
                periodSeconds: 30
  - apiVersion: v1
    kind: Service
    metadata:
      name: ${NAME}
    spec:
      ports:
        - name: http
          port: 80
          targetPort: ${{PORT}}
      selector:
        deploymentconfig: ${NAME}
      type: ClusterIP
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: ${NAME}
    spec:
      host: ${HOST_NAME}
      path: ${PATH}
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: ${NAME}
parameters:
  - name: NAME
    required: true
  - name: PROJECT 
    value: court-interpreter-scheduling
  - name: SERVICE_NAME
    value: api
  - name: CPU_LIMIT
    value: "0.5"
  - name: MEMORY_LIMIT
    value: "256M"
  - name: CPU_REQUEST
    value: "0.1"
  - name: MEMORY_REQUEST
    value: "256M"
  - name: REPLICAS
    value: "1"
  - name: PORT
    value: "3030"
  - name: DB_SERVICE
    value: patroni-master
  - name: DB_SECRET_NAME
    value: patroni-creds
  - name: DB_USERNAME_KEY
    value: superuser-username
  - name: DB_PASSWORD_KEY
    value: superuser-password
  - name: DB_NAME_KEY
    value: database-name
  - name: APP_DB
    value: court-interpreter-scheduling
  - name: IMAGE_STREAM_TAG
    required: true  
  - name: BUILD_NAMESPACE
    required: true
  - name: IMAGE_REGISTRY
    value: image-registry.openshift-image-registry.svc:5000
  - name: HOST_NAME
    required: true
  - name: PATH
    value: "/api/"
  - name: NODE_ENV
    value: "production"
  - name: JWT_SECRET
    from: "[a-zA-Z0-9]{36}"
    generate: expression
  - name: KEYCLOAK_REALM
    value: joxo7v8f
  - name: KEYCLOAK_CLIENT
    value: court-client
  - name: KEYCLOAK_URL
    required: true
  - name: DB_NAME
    required: true
  - name: DEPLOYMENT_ENV
    required: true
  - name: DEPLOYMENT_ENV_HIDDEN_FLAG
    required: true
