apiVersion: v1
kind: Template
metadata:
  labels:
    app: ${NAME}
    build: ${INSTANCE}
    template: ${NAME}-template
    project: ${PROJECT}
  name: api-court-interpreter-scheduler
parameters:
  - name: NAME
    displayName: Name
    description: A suffix appended to all objects
    required: true
    value: api-court-interpreter-scheduler
  - name: VERSION
    required: true
    value: "1.0"
  - name: CPU_LIMIT
    value: "1000m"
  - name: MEMORY_LIMIT
    value: "1Gi"
  - name: CPU_REQUEST
    value: "750m"
  - name: MEMORY_REQUEST
    value: "1Gi"
  - name: REPLICAS
    value: "1"
  - name: MAX_REPLICAS
    value: "1"
  - name: PORT
    value: "3030"
  - name: APP_PORT_DEFAULT
    value: "3030-tcp"
  - name: APP_PORT_OTHER
    value: "8080-tcp"
  - name: DB_SERVICE
    required: true
  - description: Username for PostgreSQL user that will be used for accessing the database.
    displayName: PostgreSQL Connection Username
    name: POSTGRESQL_USER
    required: true
    value: "developer"
  - name: TAG
    description: Deployment image tag
    value: "1"
  - name: BUILD_ID
    value: "1"
  - name: INSTANCE
    value: ""
  - name: HOST_NAME
    required: true
    value: "api-dev-court-interpreter-scheduler.pathfinder.gov.bc.ca"
  - name: PROJECT
    value: "api-court-interpreter-scheduler"
  - name: PATH
    required: true
    value: "/api"
objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      annotations:
        description: Nodejs Runtime Image
      labels:
        app: ${NAME}
        instance: ${INSTANCE}
        shared: "true"
        project: ${PROJECT}
      creationTimestamp: null
      generation: 0
      name: ${NAME}
    spec:
      lookupPolicy:
        local: false
    status:
      dockerImageRepository: null
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
      creationTimestamp: null
      generation: 0
      labels: 
        app: ${NAME}
        instance: ${INSTANCE}
        project: ${PROJECT}
      name: ${NAME}
    spec:
      replicas: "${{REPLICAS}}"
      revisionHistoryLimit: 10
      selector:
        deploymentConfig: ${NAME}
      strategy:
        activeDeadlineSeconds: 21600
        recreateParams:
          timeoutSeconds: 600
        resources:
          limits:
            cpu: ${CPU_LIMIT}
            memory: ${MEMORY_LIMIT}
          requests:
            cpu: ${CPU_REQUEST}
            memory: ${MEMORY_REQUEST}
        type: Rolling
      template:
        metadata:
          annotations: null
          creationTimestamp: null
          labels:
            deploymentConfig: ${NAME}
        spec:
          containers:
            - env:
                - name: BUILD_ID
                  value: ${BUILD_ID}
                - name: APPLICATION_PORT
                  value: "${PORT}"
                - name: DB_HOST
                  value: "${DB_SERVICE}"
                - name: POSTGRESQL_USER
                  valueFrom:
                    secretKeyRef:
                      key: database-user
                      name: "${DB_SERVICE}"
                - name: POSTGRESQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-password
                      name: "${DB_SERVICE}"
                - name: POSTGRESQL_DATABASE
                  valueFrom:
                    secretKeyRef:
                      key: database-name
                      name: "${DB_SERVICE}"
              image: " "
              imagePullPolicy: Always
              name: api
              ports:
                - containerPort: "${{PORT}}"
                  protocol: TCP
              resources:
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
              readinessProbe:
                failureThreshold: 10
                httpGet:
                  path: /api/v1/healthcheck
                  port: "${{PORT}}"
                  scheme: HTTP
                initialDelaySeconds: 140
                periodSeconds: 30
                successThreshold: 1
                timeoutSeconds: 20
              livenessProbe:
                failureThreshold: 10
                httpGet:
                  path: /api/v1/healthcheck
                  port: "${{PORT}}"
                  scheme: HTTP
                initialDelaySeconds: 90
                periodSeconds: 30
                successThreshold: 1
                timeoutSeconds: 20
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /opt/app-root/app
                  name: ${NAME}
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
            - emptyDir: {}
              name: ${NAME}
      test: false
      triggers:
        - imageChangeParams:
            automatic: true
            containerNames:
              - api
            from:
              kind: ImageStreamTag
              name: ${NAME}:${TAG}
          type: ImageChange
        - type: ConfigChange
    status:
      availableReplicas: 0
      latestVersion: 0
      observedGeneration: 0
      replicas: 0
      unavailableReplicas: 0
      updatedReplicas: 0
  - apiVersion: v1
    kind: Service
    metadata:
      annotations: null
      creationTimestamp: null
      labels:
        app: ${NAME}
        instance: ${INSTANCE}
        project: ${PROJECT}
      name: ${NAME}
    spec:
      ports:
        - name: ${NAME}-${APP_PORT_DEFAULT}
          port: "${{PORT}}"
          protocol: TCP
          targetPort: "${{PORT}}"
        - name: ${APP_PORT_OTHER}
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        deploymentconfig: ${NAME}
      sessionAffinity: None
      type: ClusterIP
    status:
      loadBalancer: {}
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      annotations: {}
      creationTimestamp: null
      labels:
        app: ${NAME}
        instance: ${INSTANCE}
        project: ${PROJECT}
      name: ${NAME}
    spec:
      host: ${HOST_NAME}
      path: ${PATH}
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      port:
        targetPort: ${NAME}-${APP_PORT_DEFAULT}
      to:
        kind: Service
        name: ${NAME}
        weight: 100
      wildcardPolicy: None
