---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: Deployment template for a fastapi server connected to a PostGreSQL database.
    iconClass: icon-python
    tags: fastapi
  name: ${NAME}-deployment-template
objects:
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      labels:
        app: ${APP_NAME}
        env: ${TAG_NAME}
        name: ${NAME}
      name: ${NAME}
    spec:
      description: |
        Allow the front-end application to access the API.
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  environment: ${TAG_NAME}
                  name: ${NAMESPACE_NAME}
              podSelector:
                matchLabels:
                  app: ${APP_NAME}
                  env: ${TAG_NAME}
                  role: web
          ports:
            - port: 8080
              protocol: TCP
      podSelector:
        matchLabels:
          app: ${APP_NAME}
          env: ${TAG_NAME}
          role: ${ROLE}
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        description: Exposes and load balances the application pods
        service.alpha.openshift.io/dependencies: '[{name: ${DATABASE_SERVICE_NAME}, kind: Service}]'
      labels:
        app: ${APP_NAME}
        env: ${TAG_NAME}
        name: ${NAME}
        role: ${ROLE}
      name: ${NAME}
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          targetPort: 8080
      selector:
        name: ${NAME}
  - apiVersion: v1
    kind: Secret
    metadata:
      labels:
        app: ${APP_NAME}
        env: ${TAG_NAME}
        name: ${NAME}
        role: ${ROLE}
      name: ${NAME}
    stringData:
      ADM_RECIPIENT_EMAILS: ${ADM_RECIPIENT_EMAILS}
      CHES_AUTH_URL: ${CHES_AUTH_URL}
      CHES_EMAIL_URL: ${CHES_EMAIL_URL}
      DATA_SECURITY_KEY: ${DATA_SECURITY_KEY}
      EMAIL_SERVICE_CLIENT_ID: ${EMAIL_SERVICE_CLIENT_ID}
      EMAIL_SERVICE_CLIENT_SECRET: ${EMAIL_SERVICE_CLIENT_SECRET}
      GOOGLE_MAP_URL: ${GOOGLE_MAP_URL}
      JC_INTERFACE_API_FILE_PASSWORD: ${JC_INTERFACE_API_FILE_PASSWORD}
      JC_INTERFACE_API_FILE_URL: ${JC_INTERFACE_API_FILE_URL}
      JC_INTERFACE_API_FILE_USERNAME: ${JC_INTERFACE_API_FILE_USERNAME}
      JC_INTERFACE_API_LOCATION_URL: ${JC_INTERFACE_API_LOCATION_URL}
      JC_INTERFACE_API_PASSWORD: ${JC_INTERFACE_API_PASSWORD}
      JC_INTERFACE_API_USERNAME: ${JC_INTERFACE_API_USERNAME}
      JC_INTERFACE_FILE_AGENCY_ID: ${JC_INTERFACE_FILE_AGENCY_ID}
      JC_INTERFACE_FILE_PART_ID: ${JC_INTERFACE_FILE_PART_ID}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      OIDC_RP_CLIENT_ID: ${OIDC_RP_CLIENT_ID}
      OIDC_RP_CLIENT_SECRET: ${OIDC_RP_CLIENT_SECRET}
      OIDC_RP_PROVIDER_REALM: ${OIDC_RP_PROVIDER_REALM}
      OIDC_RP_PROVIDER_URL: ${OIDC_RP_PROVIDER_URL}
      OPENROAD_MAP_URL: ${OPENROAD_MAP_URL}
      efiling-auth-realm: ${EFILING_HUB_KEYCLOAK_REALM}
      efiling-auth-url: ${EFILING_HUB_KEYCLOAK_BASE_URL}
    type: Opaque
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      annotations:
        description: Defines how to deploy the application server
      labels:
        app: ${APP_NAME}
        env: ${TAG_NAME}
        name: ${NAME}
        role: ${ROLE}
      name: ${NAME}
    spec:
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        name: ${NAME}
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: ${APP_NAME}
            env: ${TAG_NAME}
            name: ${NAME}
            role: ${ROLE}
          name: ${NAME}
        spec:
          containers:
            - env:
                - name: DEFAULT_BASE_URL
                  value: /court-interpreter-scheduling
                - name: URL_SCHEME
                  value: ${URL_SCHEME}
                - name: OIDC_RP_PROVIDER_URL
                  valueFrom:
                    secretKeyRef:
                      key: OIDC_RP_PROVIDER_URL
                      name: ${NAME}
                - name: OIDC_RP_PROVIDER_REALM
                  valueFrom:
                    secretKeyRef:
                      key: OIDC_RP_PROVIDER_REALM
                      name: ${NAME}
                - name: OIDC_RP_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      key: OIDC_RP_CLIENT_ID
                      name: ${NAME}
                - name: OIDC_RP_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      key: OIDC_RP_CLIENT_SECRET
                      name: ${NAME}
                - name: OIDC_RP_KC_IDP_HINT
                  value: ${OIDC_RP_KC_IDP_HINT}
                - name: JWT_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      key: JWT_SECRET_KEY
                      name: ${NAME}
                - name: DATABASE_ENGINE
                  value: ${DATABASE_ENGINE}
                - name: DATABASE_SERVICE_NAME
                  value: ${DATABASE_SERVICE_NAME}
                - name: DATABASE_NAME
                  valueFrom:
                    secretKeyRef:
                      key: database-name
                      name: ${DATABASE_DEPLOYMENT_NAME}
                - name: DATABASE_USER
                  valueFrom:
                    secretKeyRef:
                      key: database-user
                      name: ${DATABASE_DEPLOYMENT_NAME}
                - name: DB_SERVICE_HOST
                  value: ${DB_SERVICE_HOST}
                - name: DB_SERVICE_PORT
                  value: ${DB_SERVICE_PORT}
                - name: DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-password
                      name: ${DATABASE_DEPLOYMENT_NAME}
                - name: JC_INTERFACE_API_LOCATION_URL
                  valueFrom:
                    secretKeyRef:
                      key: JC_INTERFACE_API_LOCATION_URL
                      name: ${NAME}
                - name: JC_INTERFACE_API_USERNAME
                  valueFrom:
                    secretKeyRef:
                      key: JC_INTERFACE_API_USERNAME
                      name: ${NAME}
                - name: JC_INTERFACE_API_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: JC_INTERFACE_API_PASSWORD
                      name: ${NAME}
                - name: OPENROAD_MAP_URL
                  valueFrom:
                    secretKeyRef:
                      key: OPENROAD_MAP_URL
                      name: ${NAME}
                - name: GOOGLE_MAP_URL
                  valueFrom:
                    secretKeyRef:
                      key: GOOGLE_MAP_URL
                      name: ${NAME}
                - name: EFILING_HUB_API_BASE_URL
                  valueFrom:
                    secretKeyRef:
                      key: efiling-base-url
                      name: ${NAME}
                - name: EFILING_HUB_KEYCLOAK_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      key: efiling-client-id
                      name: ${NAME}
                - name: EFILING_HUB_KEYCLOAK_BASE_URL
                  valueFrom:
                    secretKeyRef:
                      key: efiling-auth-url
                      name: ${NAME}
                - name: EFILING_HUB_KEYCLOAK_SECRET
                  valueFrom:
                    secretKeyRef:
                      key: efiling-client-secret
                      name: ${NAME}
                - name: EFILING_HUB_KEYCLOAK_REALM
                  valueFrom:
                    secretKeyRef:
                      key: efiling-auth-realm
                      name: ${NAME}
                - name: CHES_AUTH_URL
                  valueFrom:
                    secretKeyRef:
                      key: CHES_AUTH_URL
                      name: ${NAME}
                - name: CHES_EMAIL_URL
                  valueFrom:
                    secretKeyRef:
                      key: CHES_EMAIL_URL
                      name: ${NAME}
                - name: EMAIL_SERVICE_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      key: EMAIL_SERVICE_CLIENT_ID
                      name: ${NAME}
                - name: EMAIL_SERVICE_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      key: EMAIL_SERVICE_CLIENT_SECRET
                      name: ${NAME}
                - name: RECIPIENT_EMAILS
                  valueFrom:
                    secretKeyRef:
                      key: RECIPIENT_EMAILS
                      name: ${NAME}
                - name: PDF_SERVICE_URL
                  value: ${PDF_SERVICE_URL}
                - name: ADM_RECIPIENT_EMAILS
                  valueFrom:
                    secretKeyRef:
                      key: ADM_RECIPIENT_EMAILS
                      name: ${NAME}
                - name: DATA_SECURITY_KEY
                  valueFrom:
                    secretKeyRef:
                      key: DATA_SECURITY_KEY
                      name: ${NAME}
                - name: ADM_PRODUCTION_ENV
                  value: 'true'
                - name: JC_INTERFACE_API_FILE_URL
                  valueFrom:
                    secretKeyRef:
                      key: JC_INTERFACE_API_FILE_URL
                      name: ${NAME}
                - name: JC_INTERFACE_API_FILE_USERNAME
                  valueFrom:
                    secretKeyRef:
                      key: JC_INTERFACE_API_FILE_USERNAME
                      name: ${NAME}
                - name: JC_INTERFACE_API_FILE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: JC_INTERFACE_API_FILE_PASSWORD
                      name: ${NAME}
                - name: JC_INTERFACE_FILE_PART_ID
                  valueFrom:
                    secretKeyRef:
                      key: JC_INTERFACE_FILE_PART_ID
                      name: ${NAME}
                - name: JC_INTERFACE_FILE_AGENCY_ID
                  valueFrom:
                    secretKeyRef:
                      key: JC_INTERFACE_FILE_AGENCY_ID
                      name: ${NAME}
              image: null
              imagePullPolicy: IfNotPresent
              lifecycle:
                postStart:
                  exec:
                    command:
                      - /bin/sh
                      - '-c'
                      - alembic upgrade head
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /api/v1/health
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 120
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 30
              name: ${NAME}
              ports:
                - containerPort: 8080
                  protocol: TCP
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /api/v1/health
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 3
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 30
              resources:
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
              terminationMessagePath: /${TAG_NAME}/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      test: false
      triggers:
        - imageChangeParams:
            automatic: true
            containerNames:
              - ${NAME}
            from:
              kind: ImageStreamTag
              name: ${NAME}:${TAG_NAME}
              namespace: ${IMAGE_NAMESPACE}
          type: ImageChange
        - type: ConfigChange
  - apiVersion: autoscaling/v1
    kind: HorizontalPodAutoscaler
    metadata:
      labels:
        app: ${APP_NAME}
        env: ${TAG_NAME}
        name: ${NAME}
        role: ${ROLE}
      name: ${NAME}
    spec:
      maxReplicas: ${{MAX_REPLICAS}}
      minReplicas: ${{MIN_REPLICAS}}
      scaleTargetRef:
        apiVersion: apps.openshift.io/v1
        kind: DeploymentConfig
        name: ${NAME}
parameters:
  - description: The name assigned to all of the OpenShift resources associated to the server instance.
    displayName: Name
    name: NAME
    required: true
    value: api
  - description: App Name
    displayName: App Name
    name: APP_NAME
    required: true
    value: court-interpreter-scheduling
  - description: Role
    displayName: Role
    name: ROLE
    required: true
    value: api
  - description: The base namespace name for the project.
    displayName: Namespace Name
    name: NAMESPACE_NAME
    required: true
    value: 1a7b16
  - description: The namespace of the OpenShift project containing the imagestream for the application.
    displayName: Image Namespace
    name: IMAGE_NAMESPACE
    required: true
    value: 1a7b16-tools
  - description: The name of the database server/service.
    displayName: Database Service Name
    name: DATABASE_SERVICE_NAME
    required: true
    value: db
  - description: 'Database engine: postgresql, mysql, or sqlite (default).'
    displayName: Database Engine
    name: DATABASE_ENGINE
    required: true
    value: postgresql
  - description: Internal URL to the PDF service.
    displayName: PDF Service URL
    name: PDF_SERVICE_URL
    required: true
    value: http://pdf:5001
  - description: The TAG name for this environment, e.g., dev, test, prod
    displayName: Environment TAG name
    name: TAG_NAME
    required: true
    value: dev
  - description: The name associated to the database deployment resources.  In particular, this is used to wire up the credentials associated to the database.
    displayName: Database Deployment Name
    name: DATABASE_DEPLOYMENT_NAME
    required: true
    value: db
  - description: OIDC RP Client Secret
    displayName: OIDC RP Client Secret
    name: OIDC_RP_CLIENT_SECRET
    required: false
    value: null
  - description: OIDC RP KeyCloak IDP Hint
    displayName: OIDC RP KeyCloak IDP Hint
    name: OIDC_RP_KC_IDP_HINT
    required: false
    value: bceid
  - description: The Encryption Key for the environment.
    displayName: Data Security (Encryption) Key
    from: '[a-zA-Z0-9]{32}'
    generate: expression
    name: DATA_SECURITY_KEY
  - description: EFILING authentication url
    displayName: EFILING authentication url
    name: EFILING_HUB_KEYCLOAK_BASE_URL
    required: false
    value: null
  - description: EFILING Authentication Realm
    displayName: EFILING Authentication Realm
    name: EFILING_HUB_KEYCLOAK_REALM
    required: false
    value: null
  - description: EFILING Service Client Id
    displayName: EFILING Service Client Id
    name: EFILING_HUB_KEYCLOAK_CLIENT_ID
    required: false
    value: null
  - description: EFILING Service Client Secret
    displayName: EFILING Service Client Secret
    name: EFILING_HUB_KEYCLOAK_SECRET
    required: false
    value: null
  - description: EFILING base url
    displayName: EFILING base url
    name: EFILING_HUB_API_BASE_URL
    required: false
    value: null
  - description: JC INTERFACE API LOCATION URL
    displayName: JC INTERFACE API LOCATION URL
    name: JC_INTERFACE_API_LOCATION_URL
    required: false
    value: null
  - description: JC INTERFACE API USERNAME
    displayName: JC INTERFACE API USERNAME
    name: JC_INTERFACE_API_USERNAME
    required: false
    value: null
  - description: JC INTERFACE API PASSWORD
    displayName: JC INTERFACE API PASSWORD
    name: JC_INTERFACE_API_PASSWORD
    required: false
    value: null
  - description: DEFAULT BASE URL
    displayName: DEFAULT BASE URL
    name: DEFAULT_BASE_URL
    required: false
    value: null
  - description: OPENROAD MAP URL
    displayName: OPENROAD MAP URL
    name: OPENROAD_MAP_URL
    required: false
    value: null
  - description: OIDC RP PROVIDER REALM
    displayName: OIDC RP PROVIDER REALM
    name: OIDC_RP_PROVIDER_REALM
    required: false
    value: null
  - description: OIDC RP PROVIDER URL
    displayName: OIDC RP PROVIDER URL
    name: OIDC_RP_PROVIDER_URL
    required: false
    value: null
  - description: OIDC RP CLIENT ID
    displayName: OIDC RP CLIENT ID
    name: OIDC_RP_CLIENT_ID
    required: false
    value: null
  - description: GOOGLE MAP URL
    displayName: GOOGLE MAP URL
    name: GOOGLE_MAP_URL
    required: false
    value: null
  - description: JWT SECRET KEY
    displayName: JWT SECRET KEY
    name: JWT_SECRET_KEY
    required: false
    value: null
  - description: EMAIL SERVICE CLIENT ID
    displayName: EMAIL SERVICE CLIENT ID
    name: EMAIL_SERVICE_CLIENT_ID
    required: false
    value: null
  - description: EMAIL SERVICE CLIENT SECRET
    displayName: EMAIL SERVICE CLIENT SECRET
    name: EMAIL_SERVICE_CLIENT_SECRET
    required: false
    value: null
  - description: CHES EMAIL URL
    displayName: CHES EMAIL URL
    name: CHES_EMAIL_URL
    required: false
    value: null
  - description: CHES AUTH URL
    displayName: CHES AUTH URL
    name: CHES_AUTH_URL
    required: false
    value: null
  - description: RECIPIENT EMAILS
    displayName: RECIPIENT EMAILS
    name: RECIPIENT_EMAILS
    required: false
    value: null
  - description: URL Scheme
    displayName: URL Scheme
    name: URL_SCHEME
    required: false
    value: https
  - description: Database Service Host
    displayName: Database Service Host
    name: DB_SERVICE_HOST
    required: false
    value: db
  - description: Database Service Port
    displayName: Database Service Port
    name: DB_SERVICE_PORT
    required: false
    value: '5432'
  - description: Admin Recipient Emails
    displayName: Admin Recipient Emails
    name: ADM_RECIPIENT_EMAILS
    required: false
    value: marzieh.mehrnejad@quartech.com
  - description: JC Interface API File URL
    displayName: JC Interface API File URL
    name: JC_INTERFACE_API_FILE_URL
    required: false
    value: null
  - description: JC Interface API File Username
    displayName: JC Interface API File Username
    name: JC_INTERFACE_API_FILE_USERNAME
    required: false
    value: null
  - description: JC Interface API File Password
    displayName: JC Interface API File Password
    name: JC_INTERFACE_API_FILE_PASSWORD
    required: false
    value: null
  - description: JC Interface File Part ID
    displayName: JC Interface File Part ID
    name: JC_INTERFACE_FILE_PART_ID
    required: false
    value: null
  - description: JC Interface File Agency ID
    displayName: JC Interface File Agency ID
    name: JC_INTERFACE_FILE_AGENCY_ID
    required: false
    value: null
  - description: The minimum number of pods to have running.
    displayName: Minimum Replicas
    name: MIN_REPLICAS
    required: true
    value: '3'
  - description: The maximum number of pods to have running.
    displayName: Maximum Replicas
    name: MAX_REPLICAS
    required: true
    value: '6'
  - description: The resources CPU request (in cores) for this build.
    displayName: Resources CPU Request
    name: CPU_REQUEST
    required: true
    value: 10m
  - description: The resources Memory request (in Mi, Gi, etc) for this build.
    displayName: Resources Memory Request
    name: MEMORY_REQUEST
    required: true
    value: 10Mi