import { LanguageBase } from './interfaces';

export const languages = [
  'Afghani-Dari',
  'Albanian',
  'Amharic',
  'Arabic',
  'ASL',
  'Azerbaijan-Turkish',
  'Azerbaijani',
  'Bengali',
  'Bosnian',
  'Bulgarian',
  'Burmese',
  'Cambodian (Khmer)',
  'Cantonese',
  'CART',
  'Cebuano',
  'Chiu Chow (Swatow)',
  'Croatian',
  'Czech',
  'Dari',
  'Dinka',
  'Dutch',
  'Farsi',
  'Farsi-Persian',
  'Fiji-Hindi',
  'Filipino',
  'French',
  'Fukien',
  'Fuquing',
  'Fuzhou',
  'German',
  'Greek',
  'Gujarati',
  'Hakha Chin',
  'Hakka',
  'Hebrew',
  'Hindi',
  'Hindi',
  'Hmong',
  'Hungarian',
  'Igbo',
  'Ilocano',
  'Indonesian',
  'Italian',
  'Japanese',
  'Karen',
  'Kinyarwanda',
  'Kirundi',
  'Korean',
  'Kurdish',
  'Kurdish (Kurmanji)',
  'Kurdish (Sorani)',
  'Laotian',
  'Lithuanian',
  'Malay',
  'Malayalam',
  'Mandarin',
  'Nepali',
  'Oromo',
  'Pashto',
  'Polish',
  'Portuguese',
  'Punjabi',
  'Romanian',
  'Russian',
  'Serbian',
  'Shanghainese',
  'Sinhalese',
  'Slovak',
  'Somali',
  'Spanish',
  'Sudanese',
  'Swahili',
  'Tagalog',
  'Tamil',
  'Teochew',
  'Thai',
  'Thai',
  'Tigri(gna) (yna)',
  'Turkish',
  'Ukrainian',
  'Urdu',
  'Vietnamese',
  'Vietnamese <> French',
  'Xinhui',
];

const languageByLowerCaseName: { [lowerCase: string]: string } = {};

for (const lang of languages) {
  languageByLowerCaseName[lang.toLowerCase()] = lang;
}

export function fixLanguageName<
  T extends { languageName: string; language?: string }
>(toFix: T): T {
  const language = toFix.languageName || toFix.language || '';
  return {
    ...toFix,
    languageName: languageByLowerCaseName[language.toLowerCase()] || language,
  };
}
