FROM node:12.18.3-slim

LABEL maintainer="Freshworks <web@freshworks.io>"

ENV PATH $PATH:/usr/src/app/node_modules/.bin

WORKDIR /usr/src/app

COPY ./package.json .

RUN apt-get update && apt-get -y install procps

RUN npm install

COPY . .

EXPOSE 4000

CMD [ "npm", "run", "start:dev" ]