FROM node:12.18.3-slim

LABEL maintainer="Freshworks <web@freshworks.io>"

ENV PATH $PATH:/app/node_modules/.bin

WORKDIR /app

COPY ./package.json .

RUN apt-get update && apt-get -y install procps

RUN npm install

RUN npm install -g @nestjs/cli@latest

COPY ./ .

EXPOSE 4000

CMD [ "npm", "run", "start:dev" ]
