name: Court Api Document Deploy to Github Page

on:
  push:
    branches:
      - "backend-**"

jobs:
  schemaspy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Database
        run: docker-compose up -f docker-compose.prod.yml --build api

      - name: Generate Schemaspy
        run: docker-compose up -f docker-compose.prod.yml --build schemaspy

      - name: Deploy doc folder to gh-page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./api/documentation
